export const recipes = [
    {
        id: 1,
        name: "Spaghetti Carbonara",
        chef: "Chef Mario",
        totalRatings: 500,
        avgRating: 4.8,
        uploadedOn: "2024-01-15",
        mealType: "Dinner",
        dishType: "Pasta",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A classic Italian pasta dish with a creamy egg-based sauce and crispy pancetta",
        imgUrl: "https://i.pinimg.com/564x/a9/0e/e4/a90ee4bca901e935a7a406a7d90ca6c2.jpg",
    },
    {
        id: 2,
        name: "Chicken Caesar Salad",
        chef: "Jane Smith",
        totalRatings: 200,
        avgRating: 4.5,
        uploadedOn: "2023-03-15",
        mealType: "Lunch",
        dishType: "Salad",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "A refreshing salad with grilled chicken, Caesar dressing, and crispy croutons.",
        imgUrl: "https://s23209.pcdn.co/wp-content/uploads/2023/01/220905_DD_Chx-Caesar-Salad_051-500x500.jpg",

      },
      {
        id: 3,
        name: "Chocolate Lava Cake",
        chef: "Michael Johnson",
        totalRatings: 300,
        avgRating: 4.9,
        uploadedOn: "2023-01-10",
        mealType: "Dessert",
        dishType: "Cake",
        testKitchenApproved: false,
        contestWinner: true,
        featured: true,
        description: "A rich and indulgent molten chocolate cake with a gooey center.",
        imgUrl: "https://www.lecremedelacrumb.com/wp-content/uploads/2025/02/lava-cakes-1sm-1-scaled.jpg",
      },
      {
        id: 4,
        name: "Vegetable Stir-Fry",
        chef: "Alice Brown",
        totalRatings: 180,
        avgRating: 4.3,
        uploadedOn: "2023-04-01",
        mealType: "Dinner",
        dishType: "Vegetarian",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A colorful medley of stir-fried vegetables with soy sauce and sesame oil.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpnHf_CbqUXbDtB9puaQRaiQYQN3LTggvC6w&s",
      },
      {
        id: 5,
        name: "Beef Tacos",
        chef: "Chris Green",
        totalRatings: 400,
        avgRating: 4.6,
        uploadedOn: "2023-05-10",
        mealType: "Dinner",
        dishType: "Mexican",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "Delicious soft beef tacos with guacamole, sour cream, and shredded cheese.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1RL1c36wgygzYG6KD-nc6i4BfAhJT0hJ-5Q&s",
      },
      {
        id: 6,
        name: "Grilled Salmon with Lemon Butter",
        chef: "Emily White",
        totalRatings: 250,
        avgRating: 4.8,
        uploadedOn: "2023-06-22",
        mealType: "Dinner",
        dishType: "Seafood",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A perfectly grilled salmon fillet with a creamy lemon butter sauce.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4iLTzfxUj-Q8FDhmlZ3wR7uw_f13XfGPgFA&s",
      },
      {
        id: 7,
        name: "Vegetarian Pizza",
        chef: "James Black",
        totalRatings: 220,
        avgRating: 4.4,
        uploadedOn: "2023-07-18",
        mealType: "Dinner",
        dishType: "Pizza",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "A delicious vegetarian pizza with mushrooms, bell peppers, olives, and mozzarella.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDdNxl2XCePjGkbJGl250to8KLqFKNMy1U9A&s",
      },
      {
        id: 8,
        name: "Classic Beef Burger",
        chef: "Olivia Harris",
        totalRatings: 350,
        avgRating: 4.6,
        uploadedOn: "2023-08-25",
        mealType: "Lunch",
        dishType: "Burger",
        testKitchenApproved: false,
        contestWinner: false,
        featured: false,
        description: "A juicy beef burger topped with lettuce, tomato, cheese, and pickles.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_J1lscOFdZj55mQCPmRQ4Me7fCGVZNDjN4w&s",
      },
      {
        id: 9,
        name: "Chicken Tikka Masala",
        chef: "Liam Clark",
        totalRatings: 270,
        avgRating: 4.7,
        uploadedOn: "2023-09-12",
        mealType: "Dinner",
        dishType: "Indian",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A flavorful chicken curry cooked in a rich and creamy tomato sauce.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM6Oovg0yvvYH-VI91PDQZh0NIKETsOIoojg&s",
      },
      {
        id: 10,
        name: "Fruit Smoothie",
        chef: "Sophia Lewis",
        totalRatings: 130,
        avgRating: 4.2,
        uploadedOn: "2023-02-10",
        mealType: "Breakfast",
        dishType: "Smoothie",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "A refreshing smoothie made with fresh fruits, yogurt, and honey.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnFo4AoXn82iE9YU3T0JNLWOsCvIwhOcFHVQ&s",
      },
      {
        id: 11,
        name: "Eggplant Parmesan",
        chef: "Jack Wilson",
        totalRatings: 160,
        avgRating: 4.3,
        uploadedOn: "2023-03-02",
        mealType: "Dinner",
        dishType: "Vegetarian",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "Breaded eggplant slices baked with marinara sauce and melted mozzarella.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYb82NZY5Ob2YwrqJQmTcYel6P-Jq0VjD_5A&s",
      },
      {
        id: 12,
        name: "Penne Arrabbiata",
        chef: "Ava Martinez",
        totalRatings: 280,
        avgRating: 4.8,
        uploadedOn: "2023-06-05",
        mealType: "Dinner",
        dishType: "Italian",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A spicy Italian pasta dish made with garlic, chili peppers, and tomato sauce.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRt3LDfPnZ_TkHOQjMKQKvrJ1qZCjqDPunfGg&s",
      },
      {
        id: 13,
        name: "Peking Duck",
        chef: "Lucas Taylor",
        totalRatings: 230,
        avgRating: 4.6,
        uploadedOn: "2023-09-05",
        mealType: "Dinner",
        dishType: "Chinese",
        testKitchenApproved: false,
        contestWinner: false,
        featured: false,
        description: "A traditional Chinese dish featuring crispy duck with hoisin sauce.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkFxb3h8amJntASDAgDq_pW1NRsNAE8gEspA&s",
      },
      {
        id: 14,
        name: "Shrimp Scampi",
        chef: "Charlotte Lee",
        totalRatings: 320,
        avgRating: 4.7,
        uploadedOn: "2023-07-10",
        mealType: "Dinner",
        dishType: "Seafood",
        testKitchenApproved: true,
        contestWinner: true,
        featured: true,
        description: "Shrimp cooked in a buttery, garlic sauce served over linguine pasta.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-7nQq3r6O7xQpyn66JxuDQrrUYPnBtnZZgw&s",
      },
      {
        id: 15,
        name: "Margherita Pizza",
        chef: "William Allen",
        totalRatings: 190,
        avgRating: 4.4,
        uploadedOn: "2023-08-05",
        mealType: "Lunch",
        dishType: "Pizza",
        testKitchenApproved: false,
        contestWinner: false,
        featured: false,
        description: "A classic pizza topped with fresh mozzarella, basil, and tomato sauce.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4pjh5HFOSyfgfNWWlR7TgEOUN2ZHRcUMQ5Q&s",
      },
      {
        id: 16,
        name: "Lamb Shawarma",
        chef: "Isabella Scott",
        totalRatings: 240,
        avgRating: 4.5,
        uploadedOn: "2023-10-02",
        mealType: "Dinner",
        dishType: "Middle Eastern",
        testKitchenApproved: false,
        contestWinner: false,
        featured: true,
        description: "A flavorful lamb shawarma served in a warm pita with garlic sauce and vegetables.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSB04n1DvwwBrEDViJgQCTSr58RFp8KaG4eiQ&s",
      },
      {
        id: 17,
        name: "Ratatouille",
        chef: "Chef Pierre",
        totalRatings: 450,
        avgRating: 4.3,
        uploadedOn: "2024-02-25",
        mealType: "Dinner",
        dishType: "Vegetarian",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "A French vegetable medley of zucchini, eggplant, and bell peppers, slow-cooked in a tomato-based sauce",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQI7mKQDbUzyyR5kD5cnEbd1I-76cX9nw854A&s"
    },
    {
      id: 18,
      name: "Tacos al Pastor",
      chef: "Chef Alejandro",
      totalRatings: 1100,
      avgRating: 4.9,
      uploadedOn: "2024-01-25",
      mealType: "Lunch",
      dishType: "Mexican",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Juicy marinated pork cooked on a vertical spit, served with pineapple, onions, and cilantro in soft corn tortillas",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaxiws_nODajYeoxFFeyLPwfjyezEyxDyr3w&s"
  },
]